// Mock data for UniClubs demo
export const MOCK_CLUBS = [
  {
    id: "1",
    name: "Tech Innovation Society",
    shortName: "TIS",
    category: "STEM",
    description: "A hub for tech enthusiasts to explore cutting-edge technologies, build projects, and network with industry leaders.",
    logo: "https://api.dicebear.com/9.x/shapes/svg?seed=tech",
    memberCount: 245,
    status: "active",
    membershipPolicy: "open",
    createdAt: "2024-01-15",
    tags: ["Technology", "Innovation", "Coding"],
    socialLinks: { website: "https://example.com", instagram: "@techsociety", github: "techsociety" },
    missionStatement: "Empowering students to innovate and build the future through technology.",
  },
  {
    id: "2",
    name: "Cultural Heritage Club",
    shortName: "CHC",
    category: "Cultural",
    description: "Celebrating diversity through music, dance, and cultural exchange programs that bring the campus together.",
    logo: "https://api.dicebear.com/9.x/shapes/svg?seed=cultural",
    memberCount: 312,
    status: "active",
    membershipPolicy: "open",
    createdAt: "2023-09-20",
    tags: ["Culture", "Arts", "Dance"],
    missionStatement: "Preserving and celebrating cultural heritage while fostering understanding across communities.",
  },
  {
    id: "3",
    name: "Robotics Engineering Club",
    shortName: "REC",
    category: "STEM",
    description: "Design, build, and program robots while competing in national and international competitions.",
    logo: "https://api.dicebear.com/9.x/shapes/svg?seed=robotics",
    memberCount: 89,
    status: "active",
    membershipPolicy: "approval_required",
    createdAt: "2024-02-01",
    tags: ["Robotics", "Engineering", "Competition"],
    missionStatement: "Advancing robotics knowledge through hands-on learning and competitive excellence.",
  },
  {
    id: "4",
    name: "Debate & Public Speaking",
    shortName: "DPS",
    category: "Professional",
    description: "Master the art of persuasion and public speaking through regular debates and workshops.",
    logo: "https://api.dicebear.com/9.x/shapes/svg?seed=debate",
    memberCount: 156,
    status: "active",
    membershipPolicy: "open",
    createdAt: "2023-11-10",
    tags: ["Debate", "Leadership", "Communication"],
    missionStatement: "Developing confident communicators and critical thinkers.",
  },
  {
    id: "5",
    name: "Environmental Action Group",
    shortName: "EAG",
    category: "Hobbies",
    description: "Taking action for a sustainable campus and community through projects and awareness campaigns.",
    logo: "https://api.dicebear.com/9.x/shapes/svg?seed=environment",
    memberCount: 178,
    status: "active",
    membershipPolicy: "open",
    createdAt: "2023-08-15",
    tags: ["Environment", "Sustainability", "Action"],
    missionStatement: "Creating a sustainable future through campus and community action.",
  },
  {
    id: "6",
    name: "Basketball League",
    shortName: "BBL",
    category: "Sports",
    description: "Compete, train, and improve your basketball skills with fellow enthusiasts.",
    logo: "https://api.dicebear.com/9.x/shapes/svg?seed=basketball",
    memberCount: 120,
    status: "active",
    membershipPolicy: "open",
    createdAt: "2024-01-05",
    tags: ["Sports", "Basketball", "Fitness"],
    missionStatement: "Promoting athletic excellence and sportsmanship through basketball.",
  },
  {
    id: "7",
    name: "Photography Guild",
    shortName: "PG",
    category: "Arts",
    description: "Capture moments, learn techniques, and exhibit your work with fellow photographers.",
    logo: "https://api.dicebear.com/9.x/shapes/svg?seed=photo",
    memberCount: 203,
    status: "active",
    membershipPolicy: "open",
    createdAt: "2023-10-01",
    tags: ["Photography", "Art", "Visual"],
    missionStatement: "Fostering creativity through the lens and visual storytelling.",
  },
  {
    id: "8",
    name: "Entrepreneurship Society",
    shortName: "ES",
    category: "Professional",
    description: "Turn your ideas into reality with mentorship, funding opportunities, and networking events.",
    logo: "https://api.dicebear.com/9.x/shapes/svg?seed=startup",
    memberCount: 267,
    status: "active",
    membershipPolicy: "open",
    createdAt: "2023-07-20",
    tags: ["Business", "Startup", "Innovation"],
    missionStatement: "Empowering the next generation of entrepreneurs and innovators.",
  },
]

export const MOCK_EVENTS = [
  {
    id: "e1",
    title: "Spring Innovation Fair",
    description: "Showcase your projects and innovations to the campus community.",
    date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    location: "Main Campus Hall",
    capacity: 500,
    attendeeCount: 342,
    status: "Upcoming",
    club: MOCK_CLUBS[0],
  },
  {
    id: "e2",
    title: "Cultural Night 2026",
    description: "An evening of performances celebrating diverse cultures.",
    date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    location: "University Auditorium",
    capacity: 800,
    attendeeCount: 654,
    status: "Upcoming",
    club: MOCK_CLUBS[1],
  },
  {
    id: "e3",
    title: "Robotics Workshop",
    description: "Hands-on workshop on building autonomous robots.",
    date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    location: "Engineering Lab B",
    capacity: 30,
    attendeeCount: 28,
    status: "Upcoming",
    club: MOCK_CLUBS[2],
  },
  {
    id: "e4",
    title: "Debate Championship Finals",
    description: "Watch the best debaters compete for the championship title.",
    date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    location: "Conference Center",
    capacity: 200,
    attendeeCount: 187,
    status: "Upcoming",
    club: MOCK_CLUBS[3],
  },
]

export const MOCK_USER = {
  id: "u1",
  firstName: "Alex",
  lastName: "Johnson",
  email: "alex.johnson@university.edu",
  avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=alex",
  role: "student",
  badges: ["Early Adopter", "Event Organizer"],
  clubs: [MOCK_CLUBS[0], MOCK_CLUBS[3]],
}

export const MOCK_ADMIN_STATS = {
  totalUsers: 12450,
  totalClubs: 142,
  weeklyActiveSessions: 8451,
  pendingModeration: 14,
  userGrowth: 4,
  clubGrowth: 2,
  sessionChange: -12,
}
